# material names must be as specified using the bukkit material ENUM CONSTANTS as found here: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/Material.java
farmer_material: WHEAT
fisherman_material: COD
shepard_material: WHITE_WOOL
fletcher_material: ARROW
librarian_material: BOOK
cartographer_material: FILLED_MAP
cleric_material: REDSTONE
armorer_material: GOLD_INGOT
weapon_smith_material: IRON_INGOT
tool_smith__material: STICK
butcher_material: BEEF
leatherworker_material: LEATHER
nitwit_material: RED_MUSHROOM
zombie_material: ROTTEN_FLESH

# worlds: [name of world] true|false - whether Profession is active in the world
worlds:
  world: true
  some_other_world: false

# lang: language localization for Profession messages
# english -> EN
# french -> FR
# german -> DE
# spanish -> ES
lang: EN

# consume: true|false - whether right-clicking on the villager consumes the material
consume: false
